export const SET_CURRENT_POSITION = 'SET_CURRENT_POSITION';

export const WEATHER_LOADING = 'WEATHER_LOADING';
export const WEATHER_LOADED = 'WEATHER_LOADED';
export const WEATHER_FAILURE = 'WEATHER_FAILURE';